---
dependencies:
  - common
  - edxapp_common
  - browsers
  - role: jenkins_master
    jenkins_plugins: "{{ jenkins_tools_plugins }}"
    jenkins_version: "{{ jenkins_tools_version }}"
    jenkins_deb_url: "http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb"
    jenkins_custom_plugins: []
    jenkins_bundled_plugins: "{{ jenkins_tools_bundled_plugins }}"
  # Needed to be able to build docker images. Used by Docker Image Builder Jobs.
  - role: docker-tools
    docker_users:
        - jenkins
