---
# The deadsnakes PPA is required to install python3.5 on Precise and Trusty.
# Xenial comes with python3.5 installed.
- name: add deadsnakes repository
  apt_repository:
    repo: "ppa:fkrull/deadsnakes"
  when: ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements

- name: install python3.5
  apt:
    name: "{{ item }}"
  with_items:
    - python3.5
    - python3.5-dev
  when: ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements

- name: Create sudoers file from template
  template:
    dest: "/etc/sudoers.d/99-tools_jenkins"
    src: "99-tools-jenkins.j2"
    owner: "root"
    group: "root"
    mode: "0440"
    validate: 'visudo -cf %s'
  tags:
    - install
    - install:configuration
